# collate_slats_tern_blue_biolib_agb_datasets_v1

#### Import modules

In [1]:
import pandas as pd
import os
import geopandas as gpd

In [2]:
drive = "F"
date_slats = "20230326"
date_tern = "20230326"
date_bio = "20230326"
date_blue = "20230326"

date_output = '20230326'

#### Inputs

In [3]:
# Slats data
slats_path = r"{0}:\cdu\data\output\{1}\slats_c_bio_site_totals.csv".format(drive, date_slats)
# TERN data
tern_path = r"{0}:\cdu\data\output\{1}\c_tern_bio_site_totals.csv".format(drive, date_tern)
# Tern Portal biomass - biolib
bio_path = r"{0}:\cdu\data\output\{1}\biolib_c_bio_site_totals.csv".format(drive, date_bio)
# Blue Folder biomass
blue_path = r"{0}:\cdu\data\output\{1}\blue_folders_c_bio_site_totals.csv".format(drive, date_blue)

In [4]:
output_dir = r"{0}:\cdu\data\output\{1}".format(drive, date_output)
u_output_dir = r"X:\PGB\RSU\biomass\collated_agb\{1}".format(drive, date_output)

In [5]:
# external hard drive

if not os.path.isdir(output_dir):
    os.mkdir(output_dir)

In [7]:
# internal RSU drive

# if not os.path.isdir(u_output_dir):
#     os.mkdir(u_output_dir)

#### Outputs

In [8]:
slats = pd.read_csv(slats_path)
tern = pd.read_csv(tern_path)
bio = pd.read_csv(bio_path)
blue = pd.read_csv(blue_path)

FileNotFoundError: [Errno 2] No such file or directory: 'F:\\cdu\\data\\output\\20230326\\biolib_c_bio_site_totals.csv'

In [8]:
print(f"slats shape {slats.shape}")
print(f"tern shape {tern.shape}")
print(f"biolib shape {bio.shape}")
print(f"blue shape {blue.shape}")

slats shape (104, 21)
tern shape (63, 21)
biolib shape (892, 7)
blue shape (204, 21)

In [9]:
blue

,uid,site,date,lon_gda94,lat_gda94,bio_l_kg1ha,bio_t_kg1ha,bio_b_kg1ha,bio_w_kg1ha,bio_br_kg1ha,...,bio_r_kg1ha,bio_agb_kg1ha,c_l_kg1ha,c_t_kg1ha,c_b_kg1ha,c_w_kg1ha,c_br_kg1ha,c_s_kg1ha,c_r_kg1ha,c_agb_kg1ha
0,1,LC1_1_1,20010901,131.176949,-14.018054,0.005209,0.005664,0.022129,0.071994,0.054594,...,0.031647,0.154147,0.011082,0.011559,0.045162,0.146926,0.111416,0.192088,0.064585,0.314585
1,12,LC1_2_2,20010901,131.160438,-12.210853,0.009260,0.010069,0.039341,0.127989,0.097055,...,0.056261,0.274039,0.019701,0.020549,0.080288,0.261201,0.198072,0.341489,0.114818,0.559263
2,24,FD1_1_1,20010901,131.314921,-12.561472,0.173618,0.188791,0.737647,2.399786,1.819789,...,1.054894,5.138227,0.369399,0.385288,1.505402,4.897521,3.713854,6.402923,2.152844,10.486177
3,171,LD9_2_2,20000709,131.091727,-12.703234,2.138381,2.320744,6.231289,39.489198,14.600587,...,9.904278,62.184980,4.549748,4.736213,12.716917,80.590201,29.797117,93.307118,20.212813,126.908122
4,175,LD9_1_1,20001307,131.091026,-12.702977,0.100810,0.109304,0.458236,3.844561,0.788251,...,1.139285,5.196149,0.214490,0.223070,0.935176,7.846044,1.608675,8.781220,2.325071,10.604385
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,758,BW12_1_1,20000411,135.435848,-15.572706,0.055751,0.060623,0.236867,0.770598,0.584354,...,0.338738,1.649942,0.118618,0.123720,0.483401,1.572649,1.192560,2.056050,0.691302,3.367228
200,767,BW13_2_2,20000511,135.036907,-14.908739,7.670431,8.340782,32.589243,106.022524,80.398264,...,46.605197,227.006864,16.320067,17.022005,66.508659,216.372498,164.078090,282.881157,95.112647,463.279314
201,770,BW13_1_2,20000511,135.036200,-14.908929,7.347502,7.989631,31.217220,101.558923,77.013457,...,44.643095,217.449762,15.632984,16.305370,63.708611,207.263108,157.170321,270.971719,91.108357,443.775024
202,773,BW14_2_2,20000511,135.293508,-15.170310,2.697144,2.927159,7.859537,49.807796,18.415747,...,12.492284,78.434026,5.738605,5.973793,16.039870,101.648563,37.583157,117.688433,25.494457,160.069440
203,777,BW14_1_2,20000511,135.294374,-15.170382,2.236064,2.426757,6.515938,41.293084,15.267549,...,10.356710,65.025619,4.757582,4.952565,13.297832,84.271599,31.158264,97.569431,21.136144,132.705345

In [10]:
# sorted(slats.site.unique())

In [11]:
tern.shape

(63, 21)

In [12]:
df = pd.concat([slats, tern, bio, blue])

In [13]:
df.shape

(1263, 21)

In [14]:
df

,uid,site,date,lon_gda94,lat_gda94,bio_l_kg1ha,bio_t_kg1ha,bio_b_kg1ha,bio_w_kg1ha,bio_br_kg1ha,...,bio_r_kg1ha,bio_agb_kg1ha,c_l_kg1ha,c_t_kg1ha,c_b_kg1ha,c_w_kg1ha,c_br_kg1ha,c_s_kg1ha,c_r_kg1ha,c_agb_kg1ha
0,1,lit01,20130426,131.061917,-12.547912,942.014286,1022.490000,3136.490000,14298.900000,7238.980000,...,4780.440000,25585.070000,2004.285714,2086.714286,6401.000000,29181.428570,14773.428570,35582.428570,9756.000000,52214.428570
1,6,girra02,20120605,131.132000,-12.523407,105.528429,114.751000,448.357000,1458.639000,1106.105000,...,641.186000,3123.120000,224.528571,234.185714,915.014286,2976.814286,2257.357143,3891.828571,1308.542857,6373.714286
2,24,umb07,20130603,131.674500,-13.962300,197.215357,214.025000,735.630000,4680.007500,1542.922500,...,1413.265000,7150.517500,419.607143,436.785714,1501.285714,9551.035714,3148.821429,11052.321430,2884.214286,14592.892860
3,105,jdr01,20120522,131.599700,-13.883786,458.401071,497.332500,2054.482500,15090.600000,3846.150000,...,4666.620000,21469.140000,975.321429,1014.964286,4192.821429,30797.142860,7849.285714,34989.964290,9523.714286,43814.571430
4,106,jdr02,20120523,131.600246,-13.857266,778.252857,844.900000,2442.860000,13762.840000,5792.920000,...,3794.000000,22699.390000,1655.857143,1724.285714,4985.428571,28087.428570,11822.285710,33072.857140,7742.857143,46325.285710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,758,BW12_1_1,20000411,135.435848,-15.572706,0.055751,0.060623,0.236867,0.770598,0.584354,...,0.338738,1.649942,0.118618,0.123720,0.483401,1.572649,1.192560,2.056050,0.691302,3.367228
200,767,BW13_2_2,20000511,135.036907,-14.908739,7.670431,8.340782,32.589243,106.022524,80.398264,...,46.605197,227.006864,16.320067,17.022005,66.508659,216.372498,164.078090,282.881157,95.112647,463.279314
201,770,BW13_1_2,20000511,135.036200,-14.908929,7.347502,7.989631,31.217220,101.558923,77.013457,...,44.643095,217.449762,15.632984,16.305370,63.708611,207.263108,157.170321,270.971719,91.108357,443.775024
202,773,BW14_2_2,20000511,135.293508,-15.170310,2.697144,2.927159,7.859537,49.807796,18.415747,...,12.492284,78.434026,5.738605,5.973793,16.039870,101.648563,37.583157,117.688433,25.494457,160.069440
203,777,BW14_1_2,20000511,135.294374,-15.170382,2.236064,2.426757,6.515938,41.293084,15.267549,...,10.356710,65.025619,4.757582,4.952565,13.297832,84.271599,31.158264,97.569431,21.136144,132.705345

In [15]:
site_new = []
for index, row in df.iterrows():
    site = row.site
    date = str(row.date)

    site_new.append(f"{site.lower()}_{str(date[:4])}")

df.rename(columns={"site": "site_name"}, inplace=True)
df.insert(1, "site", site_new)

In [16]:
df.sort_values(by=['site'], inplace=True)

In [17]:
df.reset_index(inplace=True, drop=True)
df["uid"] = df.index + 1
df

,uid,site,site_name,date,lon_gda94,lat_gda94,bio_l_kg1ha,bio_t_kg1ha,bio_b_kg1ha,bio_w_kg1ha,...,bio_r_kg1ha,bio_agb_kg1ha,c_l_kg1ha,c_t_kg1ha,c_b_kg1ha,c_w_kg1ha,c_br_kg1ha,c_s_kg1ha,c_r_kg1ha,c_agb_kg1ha
0,1,adelaideriver_2008,AdelaideRiver,20080905,131.117800,-13.076900,NaN,NaN,NaN,NaN,...,NaN,29730.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.673469
1,2,agb02_2012,agb02,20120417,131.005190,-12.647291,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,3,amg01_2012,amg01,20120619,134.051686,-16.380958,413.634375,448.552832,1310.224441,3748.311503,...,1811.635000,8376.216104,880.073138,915.413944,2673.927432,7649.615312,5890.702698,10323.542740,3697.214286,17094.318580
3,4,amg03_2012,amg03,20120620,134.031626,-16.778991,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,5,amg05_2012,amg05,20120621,134.090645,-16.731246,833.612143,906.465000,3541.755000,11522.385000,...,5064.990000,24670.800000,1773.642857,1849.928571,7228.071429,23515.071430,17831.785710,30743.142860,10336.714290,50348.571430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1258,1259,wh15_2012,wh15,20120727,130.948318,-17.573536,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1259,1260,ws1_1_2_2001,WS1_1_2,20012202,132.306489,-12.742793,0.174447,0.189146,0.792956,6.652832,...,1.971479,8.991689,0.371165,0.386011,1.618278,13.577208,2.783736,15.195486,4.023426,18.350387
1260,1261,ws1_2_2_2001,WS1_2_2,20012202,132.305532,-12.741944,0.267741,0.290574,0.780202,4.944328,...,1.240086,7.786001,0.569661,0.593007,1.592248,10.090465,3.730811,11.682714,2.530788,15.889798
1261,1262,ws2_1_2_2001,WS2_1_2,20012202,132.092449,-12.823036,0.212407,0.230303,0.965502,8.100475,...,2.400469,10.948264,0.451930,0.470007,1.970413,16.531582,3.389471,18.501995,4.898916,22.343396
1262,1263,ws2_2_2_2001,WS2_2_2,20012202,132.091551,-12.822710,0.174447,0.189146,0.792956,6.652832,...,1.971479,8.991689,0.371165,0.386011,1.618278,13.577208,2.783736,15.195486,4.023426,18.350387

In [18]:
#Count duplicate on certain columns
df.duplicated(subset=['site']).sum()

0

In [19]:
# Extract duplicate rows
df.loc[df.duplicated(subset=["site"]), :]

Empty DataFrame
Columns: [uid, site, site_name, date, lon_gda94, lat_gda94, bio_l_kg1ha, bio_t_kg1ha, bio_b_kg1ha, bio_w_kg1ha, bio_br_kg1ha, bio_s_kg1ha, bio_r_kg1ha, bio_agb_kg1ha, c_l_kg1ha, c_t_kg1ha, c_b_kg1ha, c_w_kg1ha, c_br_kg1ha, c_s_kg1ha, c_r_kg1ha, c_agb_kg1ha]
Index: []

[0 rows x 22 columns]

In [20]:
df.sample(20)

,uid,site,site_name,date,lon_gda94,lat_gda94,bio_l_kg1ha,bio_t_kg1ha,bio_b_kg1ha,bio_w_kg1ha,...,bio_r_kg1ha,bio_agb_kg1ha,c_l_kg1ha,c_t_kg1ha,c_b_kg1ha,c_w_kg1ha,c_br_kg1ha,c_s_kg1ha,c_r_kg1ha,c_agb_kg1ha
100,101,fa19_1_2_2000,FA19_1_2,20001010,136.270598,-12.771407,0.692886,0.751976,2.019085,12.795435,...,3.209221,20.149405,1.474226,1.534645,4.120582,26.113132,9.654971,30.233715,6.549430,41.121235
904,905,mk4_2_2_2000,MK4_2_2,20002807,131.996359,-13.652311,0.655939,0.711878,1.911420,12.113136,...,3.038093,19.074967,1.395615,1.452812,3.900858,24.720686,9.140133,28.621544,6.200191,38.928503
184,185,gulf10_2013,gulf10,20130716,136.279350,-16.025544,213.111429,231.245000,773.640000,4877.442500,...,1470.175000,7478.590000,453.428571,471.928571,1578.857143,9953.964286,3307.607143,11532.821430,3000.357143,15262.428570
1189,1190,ran2_2006,RAN2,20060101,132.907800,-12.691500,NaN,NaN,NaN,NaN,...,NaN,2884.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.886735
127,128,gre11_2_2_2000,GRE11_2_2,20003008,129.552440,-17.698330,3.835216,4.170391,16.294621,53.011262,...,23.302599,113.503432,8.160033,8.511003,33.254330,108.186249,82.039045,141.440578,47.556323,231.639657
1012,1013,nnp28_2010,NNP28,20100101,132.650600,-14.098800,NaN,NaN,NaN,NaN,...,NaN,123606.600000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,252.258367
20,21,auv06_2012,auv06,20121011,129.685010,-16.007755,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1076,1077,nnp42_2010,NNP42,20100101,132.338300,-14.061600,NaN,NaN,NaN,NaN,...,NaN,118397.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,241.627143
480,481,knp33_2005,KNP33,20050101,132.456700,-13.518200,NaN,NaN,NaN,NaN,...,NaN,405542.200000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,827.637143
1094,1095,nnp47_2000,NNP47,20000101,132.424400,-14.328800,NaN,NaN,NaN,NaN,...,NaN,869252.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1773.983673
1229,1230,umb07_2013,umb07,20130603,131.674500,-13.962300,197.215357,214.025000,735.630000,4680.007500,...,1413.265000,7150.517500,419.607143,436.785714,1501.285714,9551.035714,3148.821429,11052.321430,2884.214286,14592.892860
415,416,knp201_2009,KNP201,20090101,132.929400,-12.547200,NaN,NaN,NaN,NaN,...,NaN,343638.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,701.303469
613,614,knp77_1995,KNP77,19950101,132.300500,-13.194500,NaN,NaN,NaN,NaN,...,NaN,586680.700000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1197.307551
1067,1068,nnp40_2005,NNP40,20050101,132.553500,-14.371400,NaN,NaN,NaN,NaN,...,NaN,104639.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,213.550612
489,490,knp36_2013,KNP36,20130101,132.577000,-13.514700,NaN,NaN,NaN,NaN,...,NaN,953124.300000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1945.151633
972,973,nnp19_2010,NNP19,20100101,132.518000,-13.973700,NaN,NaN,NaN,NaN,...,NaN,66095.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.888776
108,109,fa4_1_2_2000,FA4_1_2,20002809,133.486600,-12.185266,3.079269,3.341872,8.973057,56.864446,...,14.262161,89.546371,6.551636,6.820146,18.312361,116.049889,42.907849,134.362250,29.106451,182.747696
1059,1060,nnp39_2005,NNP39,20050101,132.572000,-14.393700,NaN,NaN,NaN,NaN,...,NaN,840778.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1715.874490
188,189,hsf01_2012,hsf01,20120710,131.031329,-12.469290,864.195714,939.680000,3670.415000,12087.775000,...,5273.660000,25701.690000,1838.714286,1917.714286,7490.642857,24668.928570,18454.071430,32159.642860,10762.571430,52452.428570
263,264,knp124_2001,KNP124,20010101,132.549100,-12.812200,NaN,NaN,NaN,NaN,...,NaN,447647.800000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,913.566939

In [21]:
out = os.path.join(output_dir, "slats_tern_blue_biolib_biomass.csv")

df.to_csv(os.path.join(out), index = False)
print("file exported: ", out)

file exported:  D:\cdu\data\output\20230223\slats_tern_blue_biolib_biomass.csv

In [22]:
out = os.path.join(u_output_dir, "slats_tern_blue_biolib_biomass.csv")

df.to_csv(os.path.join(out), index = False)
print("file exported: ", out)

file exported:  X:\PGB\RSU\biomass\collated_agb\20230223\slats_tern_blue_biolib_biomass.csv

In [23]:
gdf = gpd.GeoDataFrame(
    df, geometry=gpd.points_from_xy(df.lon_gda94, df.lat_gda94))

In [24]:
gdf.set_crs("epsg:4283", inplace=True)

,uid,site,site_name,date,lon_gda94,lat_gda94,bio_l_kg1ha,bio_t_kg1ha,bio_b_kg1ha,bio_w_kg1ha,...,bio_agb_kg1ha,c_l_kg1ha,c_t_kg1ha,c_b_kg1ha,c_w_kg1ha,c_br_kg1ha,c_s_kg1ha,c_r_kg1ha,c_agb_kg1ha,geometry
0,1,adelaideriver_2008,AdelaideRiver,20080905,131.117800,-13.076900,NaN,NaN,NaN,NaN,...,29730.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60.673469,POINT (131.11780 -13.07690)
1,2,agb02_2012,agb02,20120417,131.005190,-12.647291,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (131.00519 -12.64729)
2,3,amg01_2012,amg01,20120619,134.051686,-16.380958,413.634375,448.552832,1310.224441,3748.311503,...,8376.216104,880.073138,915.413944,2673.927432,7649.615312,5890.702698,10323.542740,3697.214286,17094.318580,POINT (134.05169 -16.38096)
3,4,amg03_2012,amg03,20120620,134.031626,-16.778991,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (134.03163 -16.77899)
4,5,amg05_2012,amg05,20120621,134.090645,-16.731246,833.612143,906.465000,3541.755000,11522.385000,...,24670.800000,1773.642857,1849.928571,7228.071429,23515.071430,17831.785710,30743.142860,10336.714290,50348.571430,POINT (134.09065 -16.73125)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1258,1259,wh15_2012,wh15,20120727,130.948318,-17.573536,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,POINT (130.94832 -17.57354)
1259,1260,ws1_1_2_2001,WS1_1_2,20012202,132.306489,-12.742793,0.174447,0.189146,0.792956,6.652832,...,8.991689,0.371165,0.386011,1.618278,13.577208,2.783736,15.195486,4.023426,18.350387,POINT (132.30649 -12.74279)
1260,1261,ws1_2_2_2001,WS1_2_2,20012202,132.305532,-12.741944,0.267741,0.290574,0.780202,4.944328,...,7.786001,0.569661,0.593007,1.592248,10.090465,3.730811,11.682714,2.530788,15.889798,POINT (132.30553 -12.74194)
1261,1262,ws2_1_2_2001,WS2_1_2,20012202,132.092449,-12.823036,0.212407,0.230303,0.965502,8.100475,...,10.948264,0.451930,0.470007,1.970413,16.531582,3.389471,18.501995,4.898916,22.343396,POINT (132.09245 -12.82304)
1262,1263,ws2_2_2_2001,WS2_2_2,20012202,132.091551,-12.822710,0.174447,0.189146,0.792956,6.652832,...,8.991689,0.371165,0.386011,1.618278,13.577208,2.783736,15.195486,4.023426,18.350387,POINT (132.09155 -12.82271)

In [25]:
print(gdf.crs)

epsg:4283

In [26]:
gdf.to_file(os.path.join(output_dir, "slats_tern_blue_biolib_biomass.shp"), driver = "ESRI Shapefile")
gdf.to_file(os.path.join(u_output_dir, "slats_tern_blue_biolib_biomass.shp"), driver = "ESRI Shapefile")