# Content for Latex table

In [1]:
import pandas as pd
import geopandas as gpd
import os

In [3]:
csv_file = r"E:\cdu\data\compiled_data\tile_season_agb_si_zonal_stats.csv"

In [4]:
#dir_ = r"E:\cdu\data\roshna_data_20221019"
#dir_ = r"E:\cdu\data\slats\varified_by_rm"
output_dir = r"E:\cdu\data\output"

In [5]:
#excel_ = os.path.join(dir_, "slats_biomass_field_data_script.xlsx")

In [6]:
df = pd.read_csv(csv_file)
df

,uid,site,date,lon_gda94,lat_gda94,bio_l_kg1ha,bio_t_kg1ha,bio_b_kg1ha,bio_w_kg1ha,bio_br_kg1ha,...,NDGIt,RIt,NBRt,NDIIt,GDVIt,MSAVIt,DVIt,SAVIt,NDVIt,MSRt
0,125,nt001,20110523,131.209577,-13.945196,0.000000,0.000000,0.000000,0.0000,0.000000,...,-88149.0,88149.0,4198751.0,1377945.0,2223000.0,3797405.0,2214000.0,4028384.0,6824908.0,13019620.0
1,42,barkely01,20111025,135.040695,-18.001762,0.000000,0.000000,0.000000,0.0000,0.000000,...,-1226891.0,1226891.0,-345006.0,-1817982.0,1078000.0,1393522.0,859000.0,1638688.0,3000349.0,3628226.0
2,43,barkely02,20111026,135.259768,-18.056963,0.000000,0.000000,0.000000,0.0000,0.000000,...,-726183.0,726183.0,1441361.0,-974576.0,1221000.0,1856873.0,1112000.0,2160062.0,4085231.0,5431677.0
3,45,barkely04,20111026,135.225612,-17.984787,0.000000,0.000000,0.000000,0.0000,0.000000,...,-347222.0,347222.0,2853828.0,139556.0,1660000.0,2780839.0,1620000.0,3110599.0,5761024.0,9282429.0
4,44,barkely03,20111026,135.288375,-18.024510,0.000000,0.000000,0.000000,0.0000,0.000000,...,-147453.0,147453.0,3135436.0,269374.0,1743000.0,2841139.0,1721000.0,3134791.0,5319938.0,8092672.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
160,29,NTADAC0002,20160506,132.340300,-12.739220,59.914556,64.897778,162.650056,423.4580,330.167444,...,-1368573.0,1368573.0,1052960.0,-403029.0,1178000.0,1664492.0,989000.0,1962561.0,3864791.0,5032873.0
161,1,NTAARP0001,20160602,132.270100,-13.557290,45.895500,49.906500,194.995500,634.3785,481.057500,...,-1927320.0,1927320.0,2472185.0,168142.0,1676000.0,2230377.0,1379000.0,2517342.0,4286602.0,5813109.0
162,7,NTAARP0002,20160602,132.294400,-13.545610,39.096167,42.512944,166.107278,540.3965,409.789722,...,-2271147.0,2271147.0,-461779.0,-1352886.0,1161000.0,1238583.0,769000.0,1462533.0,2663665.0,3138328.0
163,16,NTAARP0003,20160603,132.457100,-13.516970,32.782500,35.647500,139.282500,453.1275,343.612500,...,-1878073.0,1878073.0,-4017481.0,-3915048.0,511000.0,567343.0,320000.0,735294.0,2094241.0,2368514.0
164,3,buff01,20210713,130.898593,-12.336187,343.637143,373.082500,1092.525000,5997.4075,2593.867500,...,-2740525.0,2740525.0,-5663670.0,-7143852.0,161000.0,-49679.0,-27000.0,-69266.0,-318772.0,-313850.0

In [9]:
print(list(df.columns))

['uid', 'site', 'date', 'lon_gda94', 'lat_gda94', 'bio_l_kg1ha', 'bio_t_kg1ha', 'bio_b_kg1ha', 'bio_w_kg1ha', 'bio_br_kg1ha', 'bio_s_kg1ha', 'bio_r_kg1ha', 'bio_agb_kg1ha', 'c_l_kg1ha', 'c_t_kg1ha', 'c_b_kg1ha', 'c_w_kg1ha', 'c_br_kg1ha', 'c_s_kg1ha', 'c_r_kg1ha', 'c_agb_kg1ha', 'b1_dja_min', 'b1_dja_max', 'b1_dja_mean', 'b1_dja_med', 'b1_dja_std', 'b1_dja_p25', 'b1_dja_p50', 'b1_dja_p75', 'b1_dja_p95', 'b1_dja_p99', 'b1_dbi_min', 'b1_dbi_max', 'b1_dbi_mean', 'b1_dbi_med', 'b1_dbi_std', 'b1_dbi_p25', 'b1_dbi_p50', 'b1_dbi_p75', 'b1_dbi_p95', 'b1_dbi_p99', 'b2_dbi_min', 'b2_dbi_max', 'b2_dbi_mean', 'b2_dbi_med', 'b2_dbi_std', 'b2_dbi_p25', 'b2_dbi_p50', 'b2_dbi_p75', 'b2_dbi_p95', 'b2_dbi_p99', 'b3_dbi_min', 'b3_dbi_max', 'b3_dbi_mean', 'b3_dbi_med', 'b3_dbi_std', 'b3_dbi_p25', 'b3_dbi_p50', 'b3_dbi_p75', 'b3_dbi_p95', 'b3_dbi_p99', 'b4_dbi_min', 'b4_dbi_max', 'b4_dbi_mean', 'b4_dbi_med', 'b4_dbi_std', 'b4_dbi_p25', 'b4_dbi_p50', 'b4_dbi_p75', 'b4_dbi_p95', 'b4_dbi_p99', 'b5_dbi_min', 'b5_dbi_max', 'b5_dbi_mean', 'b5_dbi_med', 'b5_dbi_std', 'b5_dbi_p25', 'b5_dbi_p50', 'b5_dbi_p75', 'b5_dbi_p95', 'b5_dbi_p99', 'b6_dbi_min', 'b6_dbi_max', 'b6_dbi_mean', 'b6_dbi_med', 'b6_dbi_std', 'b6_dbi_p25', 'b6_dbi_p50', 'b6_dbi_p75', 'b6_dbi_p95', 'b6_dbi_p99', 'b1_dim_min', 'b1_dim_max', 'b1_dim_mean', 'b1_dim_med', 'b1_dim_std', 'b1_dim_p25', 'b1_dim_p50', 'b1_dim_p75', 'b1_dim_p95', 'b1_dim_p99', 'b2_dim_min', 'b2_dim_max', 'b2_dim_mean', 'b2_dim_med', 'b2_dim_std', 'b2_dim_p25', 'b2_dim_p50', 'b2_dim_p75', 'b2_dim_p95', 'b2_dim_p99', 'b3_dim_min', 'b3_dim_max', 'b3_dim_mean', 'b3_dim_med', 'b3_dim_std', 'b3_dim_p25', 'b3_dim_p50', 'b3_dim_p75', 'b3_dim_p95', 'b3_dim_p99', 'dis_min', 'dis_max', 'dis_mean', 'dis_med', 'dis_major', 'dis_minor', 'dka_min', 'dka_max', 'dka_mean', 'dka_med', 'dka_major', 'stc_min', 'stc_max', 'stc_mean', 'stc_med', 'stc_major', 'h99a2_min', 'h99a2_max', 'h99a2_mean', 'h99a2_med', 'h99a2_std', 'h99a2_p25', 'h99a2_p50', 'h99a2_p75', 'h99a2_p95', 'h99a2_p99', 'fpca2_min', 'fpca2_max', 'fpca2_mean', 'fpca2_med', 'fpca2_std', 'fpca2_std.1', 'fpca2_p25', 'fpca2_p50', 'fpca2_p75', 'fpca2_p95', 'fpca2_p99', 'fpca2_std.2', 'fpca2_std.3', 'ratio32a', 'ratio42a', 'ratio43a', 'ratio52a', 'ratio53a', 'ratio54a', 'ratio62a', 'ratio63a', 'ratio64a', 'ratio65a', 'GSAVIa', 'GNDVIa', 'CVIa', 'NDGIa', 'RIa', 'NBRa', 'NDIIa', 'GDVIa', 'MSAVIa', 'DVIa', 'SAVIa', 'NDVIa', 'MSRa', 'b1_dbg_min', 'b1_dbg_max', 'b1_dbg_mean', 'b1_dbg_med', 'b1_dbg_std', 'b1_dbg_p25', 'b1_dbg_p50', 'b1_dbg_p75', 'b1_dbg_p95', 'b1_dbg_p99', 'b2_dbg_min', 'b2_dbg_max', 'b2_dbg_mean', 'b2_dbg_med', 'b2_dbg_std', 'b2_dbg_p25', 'b2_dbg_p50', 'b2_dbg_p75', 'b2_dbg_p95', 'b2_dbg_p99', 'b3_dbg_min', 'b3_dbg_max', 'b3_dbg_mean', 'b3_dbg_med', 'b3_dbg_std', 'b3_dbg_p25', 'b3_dbg_p50', 'b3_dbg_p75', 'b3_dbg_p95', 'b3_dbg_p99', 'b4_dbg_min', 'b4_dbg_max', 'b4_dbg_mean', 'b4_dbg_med', 'b4_dbg_std', 'b4_dbg_p25', 'b4_dbg_p50', 'b4_dbg_p75', 'b4_dbg_p95', 'b4_dbg_p99', 'b5_dbg_min', 'b5_dbg_max', 'b5_dbg_mean', 'b5_dbg_med', 'b5_dbg_std', 'b5_dbg_p25', 'b5_dbg_p50', 'b5_dbg_p75', 'b5_dbg_p95', 'b5_dbg_p99', 'b6_dbg_min', 'b6_dbg_max', 'b6_dbg_mean', 'b6_dbg_med', 'b6_dbg_std', 'b6_dbg_p25', 'b6_dbg_p50', 'b6_dbg_p75', 'b6_dbg_p95', 'b6_dbg_p99', 'b1_dp0_min', 'b1_dp0_max', 'b1_dp0_mean', 'b1_dp0_std', 'b1_dp0_med', 'b1_dp0_p25', 'b1_dp0_p50', 'b1_dp0_p75', 'b1_dp0_p95', 'b1_dp0_p99', 'b2_dp0_min', 'b2_dp0_max', 'b2_dp0_mean', 'b2_dp0_std', 'b2_dp0_med', 'b2_dp0_p25', 'b2_dp0_p50', 'b2_dp0_p75', 'b2_dp0_p95', 'b2_dp0_p99', 'b3_dp0_min', 'b3_dp0_max', 'b3_dp0_mean', 'b3_dp0_med', 'b3_dp0_p25', 'b3_dp0_p50', 'b3_dp0_p75', 'b3_dp0_p95', 'b3_dp0_p99', 'b3_dp0_std', 'b1_dp1d_min', 'b1_dp1d_max', 'b1_dp1d_mean', 'b1_dp1d_std', 'b1_dp1d_med', 'b1_dp1d_p25', 'b1_dp1d_p50', 'b1_dp1d_p75', 'b1_dp1d_p95', 'b1_dp1d_p99', 'b2_dp1d_min', 'b2_dp1d_max', 'b2_dp1d_mean', 'b2_dp1d_std', 'b2_dp1d_med', 'b2_dp1d_p25', 'b2_dp1d_p50', 'b2_dp1d_p75', 'b2_dp1d_p95', 'b2_dp1d_p99d', 'b3_dp1d_min', 'b3_dp1d_max', 'b3_dp1d_mean', 'b3_dp1d_med', 'b3_dp1d_p25', 'b3_dp1d_p50', 'b3_dp1d_p75', 'b3_dp1d_p95', 'b3_dp1d_p99', 'b3_dp1d_std', 'b1_dp1a_min', 'b1_dp1a_max', 'b1_dp1a_mean', 'b1_dp1a_std', 'b1_dp1a_med', 'b1_dp1a_p25', 'b1_dp1a_p50', 'b1_dp1a_p75', 'b1_dp1a_p95', 'b1_dp1a_p99', 'b2_dp1a_min', 'b2_dp1a_max', 'b2_dp1a_mean', 'b2_dp1a_std', 'b2_dp1a_med', 'b2_dp1a_p25', 'b2_dp1a_p50', 'b2_dp1a_p75', 'b2_dp1a_p95', 'b2_dp1a_p99', 'b3_dp1a_min', 'b3_dp1a_max', 'b3_dp1a_mean', 'b3_dp1a_med', 'b3_dp1a_p25', 'b3_dp1a_p50', 'b3_dp1a_p75', 'b3_dp1a_p95', 'b3_dp1a_p99', 'b3_dp1a_std', 'ratio32t', 'ratio42t', 'ratio43t', 'ratio52t', 'ratio53t', 'ratio54t', 'ratio62t', 'ratio63t', 'ratio64t', 'ratio65t', 'GSAVIt', 'GNDVIt', 'CVIt', 'NDGIt', 'RIt', 'NBRt', 'NDIIt', 'GDVIt', 'MSAVIt', 'DVIt', 'SAVIt', 'NDVIt', 'MSRt']

In [10]:
df1 = df[['site', 'date', 'lon_gda94', 'lat_gda94', 'bio_agb_kg1ha', 'stc_min', 'stc_max', 'stc_mean', 'stc_med']]

In [11]:
df1

,site,date,lon_gda94,lat_gda94,bio_agb_kg1ha,stc_min,stc_max,stc_mean,stc_med
0,nt001,20110523,131.209577,-13.945196,0.000000,2.0,12.0,6.7500,7.0
1,barkely01,20111025,135.040695,-18.001762,0.000000,1.0,1.0,1.0000,1.0
2,barkely02,20111026,135.259768,-18.056963,0.000000,1.0,1.0,1.0000,1.0
3,barkely04,20111026,135.225612,-17.984787,0.000000,1.0,3.0,1.8750,1.0
4,barkely03,20111026,135.288375,-18.024510,0.000000,1.0,1.0,1.0000,1.0
...,...,...,...,...,...,...,...,...,...
160,NTADAC0002,20160506,132.340300,-12.739220,978.739611,8.0,12.0,8.6250,8.0
161,NTAARP0001,20160602,132.270100,-13.557290,1358.280000,8.0,13.0,8.7000,8.5
162,NTAARP0002,20160602,132.294400,-13.545610,1157.053333,3.0,8.0,6.1875,8.0
163,NTAARP0003,20160603,132.457100,-13.516970,970.200000,3.0,8.0,4.5000,4.0
164,buff01,20210713,130.898593,-12.336187,9995.510000,NaN,NaN,NaN,NaN

In [7]:
name_list = df.site.tolist()

In [8]:
sorted(name_list)

['NTAARP0001',
 'NTAARP0002',
 'NTAARP0003',
 'NTADAC0001',
 'NTADAC0002',
 'NTAGFU0001',
 'NTAGFU0002',
 'NTAGFU0003',
 'NTAGFU0004',
 'NTAGFU0005',
 'NTAGFU0006',
 'NTAGFU0007',
 'NTAGFU0008',
 'NTAGFU0009',
 'NTAGFU0010',
 'NTAGFU0011',
 'NTAGFU0012',
 'NTAGFU0013',
 'NTAGFU0014',
 'NTAGFU0015',
 'NTAGFU0016',
 'NTAGFU0017',
 'NTAGFU0018',
 'NTAGFU0019',
 'NTAGFU0020',
 'NTAGFU0021',
 'NTAGFU0022',
 'NTAGFU0023',
 'NTAGFU0024',
 'NTAGFU0025',
 'NTAGFU0026',
 'NTAGFU0027',
 'NTAGFU0028',
 'NTAGFU0029',
 'NTAGFU0030',
 'NTAGFU0031',
 'NTAGFU0032',
 'NTAGFU0033',
 'NTAGFU0034',
 'NTAGFU0035',
 'NTAGFU0036',
 'NTAGFU0037',
 'NTAGFU0038',
 'NTAGFU0039',
 'NTAGFU0040',
 'NTAGFU0041',
 'NTAMGD0001',
 'NTAMGD0002',
 'NTAMGD0003',
 'NTAMGD0004',
 'NTAMGD0005',
 'NTAPCK0001',
 'NTAPCK0002',
 'NTASTU0001',
 'NTASTU0002',
 'NTASTU0003',
 'NTASTU0004',
 'NTASTU0005',
 'NTTDAB0001',
 'NTTDAC0001',
 'NTTMGD0001',
 'NTTPCK0001',
 'NTTSTU0001',
 'agb02',
 'amg01',
 'amg03',
 'amg05',
 'amg06',
 'amg08',
 'amg10',
 'ant01',
 'ant02',
 'ant03',
 'ant04',
 'ant06',
 'ant07',
 'ant09',
 'antgr01',
 'auv01',
 'auv02',
 'auv03',
 'auv05',
 'auv06',
 'auv07',
 'auv08',
 'barkely01',
 'barkely02',
 'barkely03',
 'barkely04',
 'barkely05',
 'barkely06',
 'barkely07',
 'buff01',
 'centa13',
 'centa14',
 'el01',
 'el02',
 'ep01',
 'girra01',
 'gulf10',
 'gulf11',
 'gulf12',
 'hsf01',
 'hsf02',
 'hshr01',
 'jdr01',
 'jdr02',
 'jdr03',
 'jdr04',
 'jdr05',
 'larr15',
 'legu01',
 'legu02',
 'legu03',
 'legu04',
 'legu05',
 'legu06',
 'legu07',
 'legu08',
 'lim01',
 'lim03',
 'lim04',
 'lim06',
 'lim08',
 'lim09',
 'lit01',
 'lto04',
 'lto05',
 'nc01',
 'nc02',
 'nc03',
 'nt001',
 'nt002',
 'nt003',
 'nt004',
 'umb07',
 'vrd16',
 'vrd17',
 'vrd20',
 'vrd22',
 'vrd23',
 'vrd24',
 'vrd25',
 'vrd26',
 'vrd29',
 'vrd30',
 'vrd31',
 'vrd32',
 'vrd33',
 'vrd34',
 'vrd35',
 'vrd36',
 'vrd37',
 'wedo01',
 'wedo03',
 'wh02',
 'wh03',
 'wh04',
 'wh05',
 'wh06',
 'wh07',
 'wh08',
 'wh09',
 'wh13',
 'wh15']

In [13]:
for i in sorted(name_list):
    print(i, "& & & \\\\")

agb02 & & & \\
amg01 & & & \\
amg02 & & & \\
amg03 & & & \\
amg05 & & & \\
amg06 & & & \\
amg08 & & & \\
amg09 & & & \\
amg10 & & & \\
ant01 & & & \\
ant02 & & & \\
ant03 & & & \\
ant04 & & & \\
ant05 & & & \\
ant06 & & & \\
ant07 & & & \\
ant09 & & & \\
antgr01 & & & \\
auv01 & & & \\
auv02 & & & \\
auv03 & & & \\
auv04 & & & \\
auv05 & & & \\
auv06 & & & \\
auv07 & & & \\
auv08 & & & \\
auv08 & & & \\
barkely01 & & & \\
barkely02 & & & \\
barkely03 & & & \\
barkely04 & & & \\
barkely05 & & & \\
barkely06 & & & \\
barkely07 & & & \\
buff01 & & & \\
centa13 & & & \\
centa14 & & & \\
el01 & & & \\
el02 & & & \\
ep01 & & & \\
girra01 & & & \\
girra02 & & & \\
gulf10 & & & \\
gulf11 & & & \\
gulf12 & & & \\
hsf01 & & & \\
hsf02 & & & \\
hshr01 & & & \\
jdr01 & & & \\
jdr02 & & & \\
jdr03 & & & \\
jdr04 & & & \\
jdr05 & & & \\
larr15 & & & \\
legu01 & & & \\
legu02 & & & \\
legu03 & & & \\
legu04 & & & \\
legu05 & & & \\
legu06 & & & \\
legu07 & & & \\
legu08 & & & \\
lim01 & & & \\
lim02 & & & \\
lim03 & & & \\
lim04 & & & \\
lim05 & & & \\
lim06 & & & \\
lim08 & & & \\
lim09 & & & \\
lit01 & & & \\
lto04 & & & \\
lto05 & & & \\
man03 & & & \\
man06 & & & \\
nc01 & & & \\
nc02 & & & \\
nc03 & & & \\
nt001 & & & \\
nt002 & & & \\
nt003 & & & \\
nt004 & & & \\
umb07 & & & \\
vrd16 & & & \\
vrd17 & & & \\
vrd18 & & & \\
vrd19 & & & \\
vrd20 & & & \\
vrd21 & & & \\
vrd22 & & & \\
vrd23 & & & \\
vrd24 & & & \\
vrd25 & & & \\
vrd26 & & & \\
vrd27 & & & \\
vrd28 & & & \\
vrd29 & & & \\
vrd30 & & & \\
vrd31 & & & \\
vrd32 & & & \\
vrd33 & & & \\
vrd34 & & & \\
vrd35 & & & \\
vrd36 & & & \\
vrd37 & & & \\
wedo01 & & & \\
wedo03 & & & \\
wh01 & & & \\
wh02 & & & \\
wh03 & & & \\
wh04 & & & \\
wh05 & & & \\
wh06 & & & \\
wh07 & & & \\
wh08 & & & \\
wh09 & & & \\
wh10 & & & \\
wh11 & & & \\
wh12 & & & \\
wh13 & & & \\
wh14 & & & \\
wh15 & & & \\